theme = "ayu_dark"

[editor]
auto-completion = true
auto-save = true
cursorline = true
completion-trigger-len = 2
idle-timeout = 750
shell = ["nu", "-c"]
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[keys.insert]
C-space = "completion"
"esc" = ["normal_mode", ":w"]
"left" = "move_char_left"
"right" = "move_char_right"
"up" = "move_line_up"
"down" = "move_line_down"

[keys.normal]
"esc" = ["collapse_selection", ":w"]
"C-r" = ":sh cargo run --release"
"C-d" = ":sh cargo run"
"C-v" = ":insert-output xclip -o"

[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":w"]